model_name: "bert-base-uncased"
dataset: "sst2"
epochs: 3
learning_rate: 2e-5
max_train_samples: 5000  # limit number of training examples for quick runs
max_eval_samples: 1000   # limit number of eval examples